server:
  port: 9000


#项目名
spring:
  application:
    name: api-gateway

#服务发送到Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    order-service: /apigateway-order/**
    product-service: /apigateway-product/**
  ignored-patterns: /**-service/**