server:
  port: 8781

#注册到服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#项目名称
spring:
  application:
    name: order-service
  #配置redis链接信息
  redis:
    database: 0
    host: 192.168.1.75
    port: 6379
    timeout: 2000

#feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 4000 #处理超时时间，默认5秒
        readTimeout: 4000 #链接超时时间，默认2秒
  #feign本身有个hystrix,默认关闭的在高版本
  hystrix:
    enabled: true

#将hystrix超时时间设置为禁止，一般不建议禁止
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#配置hystrix连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#监控仪表配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
