server:
  port: 9100

#项目名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/huwengang/xdclass-cloud.git
          username: huwengang
          password: iloveyou243.
          timeout: 5
          default-label: master

#注册到服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/