server:
  port: 9100

#项目名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/huwengang/xdclass-cloud.git
          username: huwengang
          password: iloveyou243.
          timeout: 5
          default-label: master

#注册到服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.0.16:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true